name: Format
on:
  push:
    branches: [main]

jobs:
  format:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Install go
        run: sudo apt install golang-go

      - name: Run formatter
        run: gofmt -s -w .

      - name: Save changes
        run: |
          
          if [[ -z $(git diff) ]]; then
            exit 0
          fi
          
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "format: ${{ github.event.head_commit.message }} (${{ github.sha }})"
          git push